### ISSUE TITLE
Bug in building the dictionary

### ISSUE THREAD

**Issue by milekpl** [morfologik/morfologik-stemming#10]
When building the dictionary, some lemmas are silently dropped.

The test case is attached. The form:

odgrywać|pact:pl:gen.loc:m1.m2.m3.f.n1.n2.p1.p2.p3:imperf:aff:refl.nonrefl

has no lemma in the fsa dump, even if it has a lemma in the test_file.txt. The file is here:

https://dl.dropboxusercontent.com/u/4350317/test_file.zip

**Comment by dweiss** [comment]
This was solved when encoders had been refactored (I think).
