### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by danielnaber** [morfologik/morfologik-stemming#100]
Hi, we just found another issue that affects LanguageTool and that's fixed after 2.1.4 ([#912](https://github.com/languagetool-org/languagetool/issues/912)). Are there any plans for a 2.1.5 release anytime soon?

**Comment by dweiss** [comment]
Sure think, Daniel. I'll try to do it tonight, although the connection is a bit flaky (I'm on holidays).

**Comment by dweiss** [comment]
Done!
