### ISSUE TITLE
question on building the FSA

### ISSUE THREAD

**Issue by mtrevisan** [morfologik/morfologik-stemming#105]
In FSABuilder.add:166 there is a comment: "The input must be lexicographically greater than any previously added sequence".
Why the input must be so? is there a way to relax this conditions?
I have a VERY large file to convert into FSA (1.2+ GB) and sorting it takes forever.

**Comment by dweiss** [comment]
It's a precondition of the algorithm. 1.2GB of input is not very large, man.

**Comment by dweiss** [comment]
Incremental construction of minimal acyclic finite state automata
