### ISSUE TITLE
Names of some professions have only m1 gender version

### ISSUE THREAD

**Issue by mikolajz** [morfologik/morfologik-stemming#22]
The ones I've stumbled upon are:
- [x] profesor
- [ ] komisarz
- [ ] nadkomisarz
- [ ] mecenas
- [x] dyrektor
- [ ] magister
- [ ] architekt
- [ ] redaktor
- [ ] biskup
- [ ] prezydent

I would expect there would be both m1 and f forms, with the f form not changing in declension (like it is for "doktor").

**Comment by milekpl** [comment]
profesor and dyrektor are indeed included in 2.1 but not the rest

**Comment by milekpl** [comment]
This issue was moved to morfologik/polimorfologik#7
