### ISSUE TITLE
Some adverbs not marked with degree

### ISSUE THREAD

**Issue by mikolajz** [morfologik/morfologik-stemming#23]
The ones I've found are:
- bardzo	bardzo	adv
- najbardziej	najbardziej	adv
- najpewniej	najpewniej	adv
- posuwiściej	posuwiściej	adv:pos (shouldn't that ba adv:com from posuwiście?)
- prędzej	prędzej	adv:pos (adv:com from prędko?)

I'm not sure about:
- najpierw	najpierw	adv
- najpierwej	najpierwej	adv
- pierwej	pierwej	adv
- pierwiej	pierwiej	adv

**Comment by milekpl** [comment]
This issue was moved to morfologik/polimorfologik#8
