### ISSUE TITLE
strange definition of CamelCase

### ISSUE THREAD

**Issue by danielnaber** [morfologik/morfologik-stemming#28]
`Speller.isCamelCase()` considers words like `Waschmaschinen-Test` to be camel case. If that's on purpose, it should be documented. For German, these are common words and I wouldn't consider them camel case.

**Comment by dweiss** [comment]
Is this still valid?

**Comment by danielnaber** [comment]
The issue is still valid in 1.10 and I don't see any change in the source that addresses it in 2.0. But adding a sentence to the javadoc seems a good enough fix, like `Note that German compounds with a dash (like "Waschmaschinen-Test") are also considered camel case by this method.`

**Comment by dweiss** [comment]
Can you provide a pull request for this, Daniel? I'll merge it in.

**Comment by danielnaber** [comment]
Closing, has been fixed (well, documented) long ago.
