### ISSUE TITLE
findReplacements() suboptimal results with replacement pairs

### ISSUE THREAD

**Issue by danielnaber** [morfologik/morfologik-stemming#30]
I'm not sure if the algorithm is guaranteed to return the best replacements, but this one looks like a bug. It ranks "Mitmuss" better than "Rhythmus" when the misspelled word is "Rytmus".

    public static void main(String[] args) throws Exception {
      File infoFile = new File("/tmp/morfologik.info");
      FileWriter fw1 = new FileWriter(infoFile);
      fw1.write("fsa.dict.separator=+\n");
      fw1.write("fsa.dict.encoding=utf-8\n");
      // without this, suggestions improve:
      fw1.write("fsa.dict.speller.replacement-pairs=s ss\n");
      fw1.close();
  
      File inputFile = new File("/tmp/morfologik.txt");
      FileWriter fw2 = new FileWriter(inputFile);
      fw2.write("Mitmuss\n");
      fw2.write("Rhythmus\n");
      fw2.close();
  
      File outputFile = new File("/tmp/morfologik.dict");
      String[] buildToolOptions =
              {"-i", inputFile.getAbsolutePath(), "-o", outputFile.getAbsolutePath()};
      FSABuildTool.main(buildToolOptions);
  
      Dictionary dictionary = Dictionary.read(outputFile);
      Speller speller = new Speller(dictionary, 2);
      List<String> replacements = speller.findReplacements("Rytmus");
      // -will print "[Mitmuss, Rhythmus]"
      // -will print "[Rhythmus]" if there are no replacement pairs
      // -Debugging shows that in the CandidateData constructor, 'Mitmuss' gets create with a distance of 0
      System.out.println("replacements: " + replacements);
    }

**Comment by danielnaber** [comment]
Here's another test case for the same (?) issue: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java#L297 (`testMorfologikSpeller()`)

**Comment by jaumeortola** [comment]
The problem with ist/is/die is not the same issue. It is previous to the main changes I made in the Speller (Feb 2014). Probably it is related to this [FIXME](https://github.com/morfologik/morfologik-stemming/blob/master/morfologik-speller/src/main/java/morfologik/speller/HMatrix.java#L43). The band around the diagonal of the Matrix needs to be wider, I think. Does it make sense, @milekpl?

**Comment by dweiss** [comment]
Seems to be fixed, closing. Reopen if needed.
