### ISSUE TITLE
morfologik maven plugin

### ISSUE THREAD

**Issue by pminos** [morfologik/morfologik-stemming#44]
Hello,

i wrote a maven plugin (https://github.com/pminos/morfologik-maven-plugin) for creating FSA dictionaries with morfologik-fsa. For now it can create Morphological and Synthesizer dictionaries.

I am planning to publish it to the central repository, but first I wanted to ask if you want to  merge it to morfologik-stemming. If you are interested, I can continue the development and add support for more types of dictionaries (e.g. for spelling).

**Comment by dweiss** [comment]
Why did you copy over the encoding code (and not reference the Morfologik JARs)? In any case, I think you can leave it as is in your own github location. I'd rather keep the library focused on the core functionality.
