### ISSUE TITLE
Dictionary format

### ISSUE THREAD

**Issue by Mility** [morfologik/morfologik-stemming#50]
Hi,all
I want to konw the format of morfologik's dictionaries, I think it's not just like below:
Abe+I
Abel+J
Abelard+F
Abelson+E
Aberconwy+E
I want to know more detail about it, and how to use it.
Thanks advance.

**Comment by dweiss** [comment]
The source code is the best documentation we have. Please do not open issues, use the mailing list (morfologik-devel@lists.sourceforge.net) for this type of communication.

https://github.com/morfologik/morfologik-stemming/blob/master/morfologik-stemming/src/main/java/morfologik/stemming/DictionaryLookup.java#L281

**Comment by dweiss** [comment]
The encoder actually has some more information:
https://github.com/morfologik/morfologik-stemming/blob/master/morfologik-tools/src/main/java/morfologik/tools/SequenceEncoders.java

**Comment by Mility** [comment]
Thank you very much.
