### ISSUE TITLE
OSGi plugin forks execution into insane loops

### ISSUE THREAD

**Issue by dweiss** [morfologik/morfologik-stemming#64]
The osgi (BND) plugin forks the execution of targets into insane loops (multiple runs of tests, javadocs, etc.). 

I will remove the OSGi plugin from the build. If somebody needs it and knows how to make it work cleanly with Maven, submit a patch.

**Comment by dweiss** [comment]
Perhaps you'll know how to fix this, @hlavki.

**Comment by hlavki** [comment]
I searched and found that it's known and already fixed issue in maven-bundle-plugin (https://issues.apache.org/jira/browse/FELIX-4882). It works properly with maven-bundle-plugin version 2.5.5-SNAPSHOT

**Comment by dweiss** [comment]
Ok, let's wait until 2.5.5 is available then. Thanks for digging.

**Comment by dweiss** [comment]
They seem to have skipped to 3.0.0. I've updated the code and everything seems to be back to normal, thanks for researching this, Michal.
