### ISSUE TITLE
Vocative of village name "Bystra" should be "Bystro"

### ISSUE THREAD

**Issue by mikolajz** [morfologik/morfologik-stemming#67]
The lexicon contains both a lower-case common adjective whose vocative is correctly "bystra", but also an uppercase words which can be the village name and should IMHO have the vocative "Bystro".

**Comment by dweiss** [comment]
Mikołaj, could you report data-related issues here instead?
https://github.com/morfologik/polimorfologik/issues

I think this would be a better place to correct them and perhaps @milekpl can chip in as to how the morfologik dictionary is currently built and what the source of the data is (the way it used to be was that scripts would generate inflection from annotated forms, but I've no idea how it is done at the moment).

**Comment by mikolajz** [comment]
I was told at some point to open them here, but if the other place is better, I will use the other component.

**Comment by dweiss** [comment]
That was before I created that other project I think. I think I'd like to keep the issues related to the underlying dictionary separate from the codebase. I know very little about how the dictionary was created and how it's maintained -- Marcin has been taking care of that.
