### ISSUE TITLE
Dictionary thread-safe

### ISSUE THREAD

**Issue by danielnaber** [morfologik/morfologik-stemming#69]
This is more of a question: is `Dictionary` thread-safe or are there any plans to guarantee its thread-safety? Here's my use case: I create a `Dictionary` at runtime, which takes some time, so I'd like to do it only once and use it for all threads.

**Comment by dweiss** [comment]
Dictionary is thread safe (it's essentially the automaton and associated metadata). DictionaryLookup isn't thread safe, but is cheap to create and dispose (so it makes no sense to cache).

**Comment by danielnaber** [comment]
Great - assuming that's not going to change, I suggest adding that information to the Javadoc (both to Dictionary and DictionaryLookup).
