### ISSUE TITLE
Trailing spaces in encoder name can lead to illegal argument exception

### ISSUE THREAD

**Issue by jaumeortola** [morfologik/morfologik-stemming#77]
A trailing space in "fsa.dict.encoder=SUFFIX " causes an error: "java.lang.IllegalArgumentException: No enum constant morfologik.stemming.EncoderType.SUFFIX ". This should be fixed. The cause of the error was very hard to find.

**Comment by dweiss** [comment]
These are standard Java property files, we don't do the parsing. I can add a trim before value lookup though, this should help (and we know it's a constant).
