### ISSUE TITLE
Misleading DictionaryMetadataBuilder option name

### ISSUE THREAD

**Issue by mkopec87** [morfologik/morfologik-stemming#82]
Hi, 

I find DictionaryMetadataBuilder frequencyIncluded() option misleading, one may expect that it would mean that frequency WILL be included, but in fact it is not.

All best,
Mateusz

**Comment by dweiss** [comment]
This looks like a bug to me indeed. Care to provide a pull request?

**Comment by mkopec87** [comment]
I did. This is my first pull request on GitHub ever, so please tell me if I did anything wrong :)

**Comment by dweiss** [comment]
Fixed in PR83. 

bq. This is my first pull request on GitHub ever,

Well, congratulations -- you're off for a good start!
