### ISSUE TITLE
replacement-pairs fail at end of word

### ISSUE THREAD

**Issue by danielnaber** [morfologik/morfologik-stemming#91]
It seems replacement pairs, at least when of different length, fail at the end of a word. E.g. "Fux" doesn't suggest "Fuchs" even with `fsa.dict.speller.replacement-pairs=x chs`. Adding two more characters at the end of the word makes it work (i.e. `Fuxee` suggests `Fuchsee`, both are fantasy words).

I've added a stand-alone example here in LanguageTool: https://github.com/languagetool-org/languagetool/blob/6d38df7eda58bfc6b796d91e35fc7debda57f7d5/languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java#L369

Maybe this is related to [this comment](https://github.com/morfologik/morfologik-stemming/issues/30#issuecomment-54267720). If this is actually a bug and won't be fixed, it should be documented.

**Comment by jaumeortola** [comment]
It is probably related to the previous bug you mention. I will take a look, but I foresee it will be difficult to fix.

**Comment by jaumeortola** [comment]
[This](https://github.com/morfologik/morfologik-stemming/pull/93/commits/145ad6b8fd20c5c0b02f3768932fea5a561986dd) fixes the problem. There is no reason not to try replacements in short words.

**Comment by dweiss** [comment]
(Released the fix in 2.1.4)
