### ISSUE TITLE
uppercase suggestion prevents other good suggestion

### ISSUE THREAD

**Issue by danielnaber** [morfologik/morfologik-stemming#94]
German "schänke" should suggest "schenke" and "Schänke", but it only suggests "Schänke". The issue seems to be that "Schänke" is found first and then `if (candidates.isEmpty())` isn't true anymore. Here's a test:

https://github.com/languagetool-org/languagetool/blob/6fba53be36bc66ddf3ed8d7410b91430912c563f/languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java#L409-L427

**Comment by dweiss** [comment]
I don't know much about the Speller module; @jaumeortola ?

**Comment by dweiss** [comment]
Is this issue still valid? Daniel -- you seem to know more about the speller than I do; if you can modify the code and provide a patch, please go ahead!

**Comment by danielnaber** [comment]
The issue is still valid. I'll see if I can provide a patch.
